### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by rohit-vishwakarma** [rohit-vishwakarma/neetouichallenge#35]
Deployed at [Heroku](https://neetoui-rohit-vishwakarma.herokuapp.com/)
Can be logged in using:
Username : oliver@example.com
Password : welcome

@yedhink Please review

**Comment by yedhink** [comment]
@rohit-vishwakarma I had given some reviews for your closed PRs. Once you address/fix them lemme know over here.

**Comment by rohit-vishwakarma** [comment]
I have fixed the issues according to the PR reviews. Please have a look at it and let me know if you have any other feedback.

**Comment by yedhink** [comment]
@rohit-vishwakarma 

- [ ] The validation error message and resource doesn't match:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/31244999/191242382-6134f7e6-054f-49de-83e8-5cb40d81bbc0.png">

Rest LGTM. You can fix this issue and mark this task as completed and continue with the next task.
